- name: Install Zabbix repo
  apt:
    deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb

- name: Update cache
  apt:
    update_cache: yes

- name: Install agent
  apt:
    name: zabbix-agent
    state: present

- name: Configure Zabbix agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Restart agent
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: true
